import { Inter } from "next/font/google";
import "./globals.css";

import { PrimeReactProvider } from 'primereact/api';
// Estilos de PrimeReact
import 'primereact/resources/themes/lara-dark-cyan/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';

// Contexto
import { FileProvider } from "./context/fileContex";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <FileProvider>

      <PrimeReactProvider>
        <html lang="en">
          <body className={`${inter.className} m-6 mx-8 `}>{children}</body>
        </html>
      </PrimeReactProvider>
    </FileProvider>
  );
}
